export const metros = {
  '662': 'Abilene-Sweetwater',
  '525': 'Albany, GA',
  '532': 'Albany-Schenectady-Troy',
  '790': 'Albuquerque-Santa Fe',
  '644': 'Alexandria, LA',
  '583': 'Alpena',
  '634': 'Amarillo',
  '524': 'Atlanta',
  '520': 'Augusta-Aiken',
  '635': 'Austin',
  '800': 'Bakersfield',
  '512': 'Baltimore',
  '537': 'Bangor',
  '716': 'Baton Rouge',
  '692': 'Beaumont-Port Arthur',
  '821': 'Bend, OR',
  '756': 'Billings',
  '746': 'Biloxi-Gulfport',
  '502': 'Binghamton',
  '630': 'Birmingham (Anniston And Tuscaloosa)',
  '559': 'Bluefield-Beckley-Oak Hill',
  '757': 'Boise',
  '506': 'Boston (Manchester)',
  '736': 'Bowling Green',
  '514': 'Buffalo',
  '523': 'Burlington-Plattsburgh',
  '754': 'Butte-Bozeman',
  '767': 'Casper-Riverton',
  '637': 'Cedar Rapids-Waterloo-Iowa City & Dubuque',
  '648': 'Champaign & Springfield-Decatur',
  '519': 'Charleston, SC',
  '564': 'Charleston-Huntington',
  '517': 'Charlotte',
  '584': 'Charlottesville',
  '575': 'Chattanooga',
  '759': 'Cheyenne-Scottsbluff',
  '602': 'Chicago',
  '868': 'Chico-Redding',
  '515': 'Cincinnati',
  '598': 'Clarksburg-Weston',
  '510': 'Cleveland-Akron (Canton)',
  '752': 'Colorado Springs-Pueblo',
  '546': 'Columbia, SC',
  '604': 'Columbia-Jefferson City',
  '522': 'Columbus, GA (Opelika, AL)',
  '535': 'Columbus, OH',
  '673': 'Columbus-Tupelo-West Point-Houston',
  '600': 'Corpus Christi',
  '623': 'Dallas-Ft. Worth',
  '682': 'Davenport-Rock Island-Moline',
  '542': 'Dayton',
  '751': 'Denver',
  '679': 'Des Moines-Ames',
  '505': 'Detroit',
  '606': 'Dothan',
  '676': 'Duluth-Superior',
  '765': 'El Paso (Las Cruces)',
  '565': 'Elmira (Corning)',
  '516': 'Erie',
  '801': 'Eugene',
  '802': 'Eureka',
  '649': 'Evansville',
  '724': 'Fargo-Valley City',
  '513': 'Flint-Saginaw-Bay City',
  '866': 'Fresno-Visalia',
  '571': 'Ft. Myers-Naples',
  '670': 'Ft. Smith-Fayetteville-Springdale-Rogers',
  '509': 'Ft. Wayne',
  '592': 'Gainesville',
  '798': 'Glendive',
  '773': 'Grand Junction-Montrose',
  '563': 'Grand Rapids-Kalamazoo-Battle Creek',
  '755': 'Great Falls',
  '658': 'Green Bay-Appleton',
  '518': 'Greensboro-High Point-Winston Salem',
  '545': 'Greenville-New Bern-Washington',
  '567': 'Greenville-Spartanburg-Asheville-Anderson',
  '647': 'Greenwood-Greenville',
  '636': 'Harlingen-Weslaco-Brownsville-Mcallen',
  '566': 'Harrisburg-Lancaster-Lebanon-York',
  '569': 'Harrisonburg',
  '533': 'Hartford & New Haven',
  '710': 'Hattiesburg-Laurel',
  '766': 'Helena',
  '618': 'Houston',
  '691': 'Huntsville-Decatur (Florence)',
  '758': 'Idaho Falls-Pocatello (Jackson)',
  '527': 'Indianapolis',
  '718': 'Jackson, MS',
  '639': 'Jackson, TN',
  '561': 'Jacksonville',
  '574': 'Johnstown-Altoona-State College',
  '734': 'Jonesboro',
  '603': 'Joplin-Pittsburg',
  '616': 'Kansas City',
  '557': 'Knoxville',
  '702': 'La Crosse-Eau Claire',
  '582': 'Lafayette, IN',
  '642': 'Lafayette, LA',
  '643': 'Lake Charles',
  '551': 'Lansing',
  '749': 'Laredo',
  '839': 'Las Vegas',
  '541': 'Lexington',
  '558': 'Lima',
  '722': 'Lincoln & Hastings-Kearney',
  '693': 'Little Rock-Pine Bluff',
  '803': 'Los Angeles',
  '529': 'Louisville',
  '651': 'Lubbock',
  '503': 'Macon',
  '669': 'Madison',
  '737': 'Mankato',
  '553': 'Marquette',
  '813': 'Medford-Klamath Falls',
  '640': 'Memphis',
  '711': 'Meridian',
  '528': 'Miami-Ft. Lauderdale',
  '617': 'Milwaukee',
  '613': 'Minneapolis-St. Paul',
  '687': 'Minot-Bismarck-Dickinson',
  '762': 'Missoula',
  '686': 'Mobile-Pensacola (Ft. Walton Beach)',
  '628': 'Monroe-El Dorado',
  '828': 'Monterey-Salinas',
  '698': 'Montgomery-Selma',
  '570': 'Myrtle Beach-Florence',
  '659': 'Nashville',
  '622': 'New Orleans',
  '501': 'New York',
  '544': 'Norfolk-Portsmouth-Newport News',
  '740': 'North Platte',
  '633': 'Odessa-Midland',
  '650': 'Oklahoma City',
  '652': 'Omaha',
  '534': 'Orlando-Daytona Beach-Melbourne',
  '631': 'Ottumwa-Kirksville',
  '632': 'Paducah-Cape Girardeau-Harrisburg',
  '804': 'Palm Springs',
  '656': 'Panama City',
  '597': 'Parkersburg',
  '675': 'Peoria-Bloomington',
  '504': 'Philadelphia',
  '753': 'Phoenix (Prescott)',
  '508': 'Pittsburgh',
  '820': 'Portland, OR',
  '500': 'Portland-Auburn',
  '552': 'Presque Isle',
  '521': 'Providence-New Bedford',
  '717': 'Quincy-Hannibal-Keokuk',
  '560': 'Raleigh-Durham (Fayetteville)',
  '764': 'Rapid City',
  '811': 'Reno',
  '556': 'Richmond-Petersburg',
  '573': 'Roanoke-Lynchburg',
  '538': 'Rochester, NY',
  '611': 'Rochester-Mason City-Austin',
  '610': 'Rockford',
  '862': 'Sacramento-Stockton-Modesto',
  '576': 'Salisbury',
  '770': 'Salt Lake City',
  '661': 'San Angelo',
  '641': 'San Antonio',
  '825': 'San Diego',
  '807': 'San Francisco-Oakland-San Jose',
  '855': 'Santa Barbara-Santa Maria-San Luis Obispo',
  '507': 'Savannah',
  '819': 'Seattle-Tacoma',
  '657': 'Sherman-Ada',
  '612': 'Shreveport',
  '624': 'Sioux City',
  '725': 'Sioux Falls (Mitchell)',
  '588': 'South Bend-Elkhart',
  '881': 'Spokane',
  '619': 'Springfield, MO',
  '543': 'Springfield-Holyoke',
  '638': 'St. Joseph',
  '609': 'St. Louis',
  '555': 'Syracuse',
  '530': 'Tallahassee-Thomasville',
  '539': 'Tampa-St. Petersburg (Sarasota)',
  '581': 'Terre Haute',
  '547': 'Toledo',
  '605': 'Topeka',
  '540': 'Traverse City-Cadillac',
  '531': 'Tri-Cities, TN-VA',
  '789': 'Tucson (Sierra Vista)',
  '671': 'Tulsa',
  '760': 'Twin Falls',
  '709': 'Tyler-Longview (Lufkin & Nacogdoches)',
  '526': 'Utica',
  '626': 'Victoria',
  '625': 'Waco-Temple-Bryan',
  '511': 'Washington, DC (Hagerstown)',
  '549': 'Watertown',
  '705': 'Wausau-Rhinelander',
  '548': 'West Palm Beach-Ft. Pierce',
  '554': 'Wheeling-Steubenville',
  '627': 'Wichita Falls & Lawton',
  '678': 'Wichita-Hutchinson Plus',
  '577': 'Wilkes Barre-Scranton',
  '550': 'Wilmington',
  '810': 'Yakima-Pasco-Richland-Kennewick',
  '536': 'Youngstown',
  '771': 'Yuma-El Centro',
  '596': 'Zanesville',
  '743': 'Anchorage',
  '745': 'Fairbanks',
  '747': 'Juneau',
  '744': 'Honolulu',
}

const flags = {
  AF: '🇦🇫',
  AO: '🇦🇴',
  AL: '🇦🇱',
  AD: '🇦🇩',
  AE: '🇦🇪',
  AR: '🇦🇷',
  AM: '🇦🇲',
  AG: '🇦🇬',
  AU: '🇦🇺',
  AT: '🇦🇹',
  AZ: '🇦🇿',
  BI: '🇧🇮',
  BE: '🇧🇪',
  BJ: '🇧🇯',
  BF: '🇧🇫',
  BD: '🇧🇩',
  BG: '🇧🇬',
  BH: '🇧🇭',
  BS: '🇧🇸',
  BA: '🇧🇦',
  BY: '🇧🇾',
  BZ: '🇧🇿',
  BO: '🇧🇴',
  BR: '🇧🇷',
  BB: '🇧🇧',
  BN: '🇧🇳',
  BT: '🇧🇹',
  BW: '🇧🇼',
  CF: '🇨🇫',
  CA: '🇨🇦',
  CH: '🇨🇭',
  CL: '🇨🇱',
  CN: '🇨🇳',
  CI: '🇨🇮',
  CM: '🇨🇲',
  CD: '🇨🇩',
  CG: '🇨🇬',
  CO: '🇨🇴',
  KM: '🇰🇲',
  CV: '🇨🇻',
  CR: '🇨🇷',
  CU: '🇨🇺',
  CY: '🇨🇾',
  CZ: '🇨🇿',
  DE: '🇩🇪',
  DJ: '🇩🇯',
  DM: '🇩🇲',
  DK: '🇩🇰',
  DO: '🇩🇴',
  DZ: '🇩🇿',
  EC: '🇪🇨',
  EG: '🇪🇬',
  ER: '🇪🇷',
  ES: '🇪🇸',
  EE: '🇪🇪',
  ET: '🇪🇹',
  FI: '🇫🇮',
  FJ: '🇫🇯',
  FR: '🇫🇷',
  FM: '🇫🇲',
  GA: '🇬🇦',
  GB: '🇬🇧',
  GE: '🇬🇪',
  GH: '🇬🇭',
  GN: '🇬🇳',
  GM: '🇬🇲',
  GW: '🇬🇼',
  GQ: '🇬🇶',
  GR: '🇬🇷',
  GD: '🇬🇩',
  GT: '🇬🇹',
  GY: '🇬🇾',
  HN: '🇭🇳',
  HR: '🇭🇷',
  HT: '🇭🇹',
  HU: '🇭🇺',
  ID: '🇮🇩',
  IN: '🇮🇳',
  IE: '🇮🇪',
  IR: '🇮🇷',
  IQ: '🇮🇶',
  IS: '🇮🇸',
  IL: '🇮🇱',
  IT: '🇮🇹',
  JM: '🇯🇲',
  JO: '🇯🇴',
  JP: '🇯🇵',
  KZ: '🇰🇿',
  KE: '🇰🇪',
  KG: '🇰🇬',
  KH: '🇰🇭',
  KI: '🇰🇮',
  KN: '🇰🇳',
  KR: '🇰🇷',
  KW: '🇰🇼',
  LA: '🇱🇦',
  LB: '🇱🇧',
  LR: '🇱🇷',
  LY: '🇱🇾',
  LC: '🇱🇨',
  LI: '🇱🇮',
  LK: '🇱🇰',
  LS: '🇱🇸',
  LT: '🇱🇹',
  LU: '🇱🇺',
  LV: '🇱🇻',
  MA: '🇲🇦',
  MC: '🇲🇨',
  MD: '🇲🇩',
  MG: '🇲🇬',
  MV: '🇲🇻',
  MX: '🇲🇽',
  MH: '🇲🇭',
  MK: '🇲🇰',
  ML: '🇲🇱',
  MT: '🇲🇹',
  MM: '🇲🇲',
  ME: '🇲🇪',
  MN: '🇲🇳',
  MZ: '🇲🇿',
  MR: '🇲🇷',
  MU: '🇲🇺',
  MW: '🇲🇼',
  MY: '🇲🇾',
  NA: '🇳🇦',
  NE: '🇳🇪',
  NG: '🇳🇬',
  NI: '🇳🇮',
  NL: '🇳🇱',
  NO: '🇳🇴',
  NP: '🇳🇵',
  NR: '🇳🇷',
  NZ: '🇳🇿',
  OM: '🇴🇲',
  PK: '🇵🇰',
  PA: '🇵🇦',
  PE: '🇵🇪',
  PH: '🇵🇭',
  PW: '🇵🇼',
  PG: '🇵🇬',
  PL: '🇵🇱',
  KP: '🇰🇵',
  PT: '🇵🇹',
  PY: '🇵🇾',
  QA: '🇶🇦',
  RO: '🇷🇴',
  RU: '🇷🇺',
  RW: '🇷🇼',
  SA: '🇸🇦',
  SD: '🇸🇩',
  SN: '🇸🇳',
  SG: '🇸🇬',
  SB: '🇸🇧',
  SL: '🇸🇱',
  SV: '🇸🇻',
  SM: '🇸🇲',
  SO: '🇸🇴',
  RS: '🇷🇸',
  SS: '🇸🇸',
  ST: '🇸🇹',
  SR: '🇸🇷',
  SK: '🇸🇰',
  SI: '🇸🇮',
  SE: '🇸🇪',
  SZ: '🇸🇿',
  SC: '🇸🇨',
  SY: '🇸🇾',
  TD: '🇹🇩',
  TG: '🇹🇬',
  TH: '🇹🇭',
  TJ: '🇹🇯',
  TM: '🇹🇲',
  TL: '🇹🇱',
  TO: '🇹🇴',
  TT: '🇹🇹',
  TN: '🇹🇳',
  TR: '🇹🇷',
  TV: '🇹🇻',
  TZ: '🇹🇿',
  UG: '🇺🇬',
  UA: '🇺🇦',
  UY: '🇺🇾',
  US: '🇺🇸',
  UZ: '🇺🇿',
  VA: '🇻🇦',
  VC: '🇻🇨',
  VE: '🇻🇪',
  VN: '🇻🇳',
  VU: '🇻🇺',
  WS: '🇼🇸',
  YE: '🇾🇪',
  ZA: '🇿🇦',
  ZM: '🇿🇲',
  ZW: '🇿🇼',
}